import type { Destination } from '@/lib/types'

export const mockDestinations: Destination[] = [
  {
    id: 'ai-ml-engineer',
    title: 'AI / ML Engineer',
    category: 'Technical',
    description: 'Build production machine learning systems, large neural models, and AI pipelines.',
    icon: '🧠',
    requiredSkillCount: 19,
    avgSalary: '₹14-25 LPA',
    tags: ['Python', 'Deep Learning', 'Statistics', 'MLOps'],
    resources: [
      { title: 'Fast.ai Practical Deep Learning', type: 'Course', provider: 'Fast.ai' },
      { title: 'CS229: Machine Learning', type: 'Course', provider: 'Stanford University' },
      { title: 'Deep Learning Specialization', type: 'Course', provider: 'Coursera (Andrew Ng)' },
      { title: 'Hands-On ML with Scikit-Learn & PyTorch', type: 'Book', provider: 'O’Reilly' },
    ],
  },
  {
    id: 'mtech-gate',
    title: 'M.Tech & GATE Specialist (IITs / IISc)',
    category: 'Higher Studies',
    description: 'Master advanced computing disciplines at premier institutes (IITs/IISc) or secure direct PSU recruitments (ISRO, BARC, ONGC, IOCL).',
    icon: '🏛️',
    requiredSkillCount: 14,
    avgSalary: '₹18-32 LPA / PSU Grade A',
    tags: ['Algorithms', 'TOC & Compilers', 'OS & DBMS', 'Engg Math'],
    resources: [
      { title: 'Official GATE Portal (IIT Organising)', type: 'Exam Portal', provider: 'gate.iitk.ac.in' },
      { title: 'NPTEL Computer Science Lecture Series', type: 'Course', provider: 'IIT Madras & IISc' },
      { title: 'GeeksforGeeks GATE CS Subject Roadmaps', type: 'Practice', provider: 'GFG GATE' },
      { title: 'Made Easy / ACE Academy GATE CS Question Banks', type: 'Book', provider: 'Standard Technical' },
    ],
  },
  {
    id: 'foreign-studies-ms',
    title: 'Foreign Studies & MS Abroad (US / EU / Germany)',
    category: 'Higher Studies',
    description: 'Pursue Master of Science in Computer Science or Data Science at top global universities (CMU, Stanford, TUM, ETH Zurich).',
    icon: '✈️',
    requiredSkillCount: 12,
    avgSalary: '$110,000 - $160,000 / yr',
    tags: ['GRE General', 'TOEFL / IELTS', 'Research SOP', 'CGPA 8.5+'],
    resources: [
      { title: 'ETS GRE Official Guide & Prep', type: 'Official Guide', provider: 'ets.org/gre' },
      { title: 'DAAD Germany International Degree Finder (Tuition-Free)', type: 'Official Guide', provider: 'daad.de' },
      { title: 'GregMat GRE Verbal & Quant Strategy', type: 'Course', provider: 'GregMat' },
      { title: 'Yocket & GradCafe University Profile Evaluation', type: 'Practice', provider: 'Yocket' },
    ],
  },
  {
    id: 'mba-tech-mgmt',
    title: 'MBA & Product Management (IIMs / CAT / GMAT)',
    category: 'Management',
    description: 'Transition from engineering to strategic leadership, Product Management, Consulting, and Executive Business roles.',
    icon: '💼',
    requiredSkillCount: 13,
    avgSalary: '₹22-38 LPA',
    tags: ['CAT / GMAT', 'Data Interpretation', 'Product Sense', 'Quantitative Aptitude'],
    resources: [
      { title: 'IIM Common Admission Test (CAT) Portal', type: 'Exam Portal', provider: 'iimcat.ac.in' },
      { title: 'GMAT Club Practice Questions & CAT Mocks', type: 'Practice', provider: 'GMAT Club / TIME / IMS' },
      { title: 'Decode and Conquer (Product Management Interviews)', type: 'Book', provider: 'Lewis C. Lin' },
      { title: 'Inspired: How to Create Tech Products Customers Love', type: 'Book', provider: 'Marty Cagan' },
    ],
  },
  {
    id: 'civil-services-ias',
    title: 'Civil Services / IAS / Public Policy (UPSC CSE)',
    category: 'Public Services',
    description: 'Serve the nation as an IAS/IPS/IFS officer or policy architect through the prestigious UPSC Civil Services Examination.',
    icon: '🇮🇳',
    requiredSkillCount: 16,
    avgSalary: 'Level 10 Pay Matrix + Prestigious Office',
    tags: ['UPSC CSE', 'General Studies (GS I-IV)', 'CSAT', 'Optional Subject'],
    resources: [
      { title: 'UPSC Official Portal & Syllabus', type: 'Official Guide', provider: 'upsc.gov.in' },
      { title: 'NCERT Textbooks (Class 6-12 Core Foundations)', type: 'Book', provider: 'ncert.nic.in' },
      { title: 'Indian Polity by M. Laxmikanth', type: 'Book', provider: 'McGraw Hill' },
      { title: 'The Hindu / Indian Express Daily Editorial Analysis', type: 'Practice', provider: 'National Press' },
      { title: 'Vision IAS / InsightsIAS Daily Current Affairs', type: 'Course', provider: 'Open Academic' },
    ],
  },
  {
    id: 'research-phd',
    title: 'Academic & Industrial Research / PhD',
    category: 'Research',
    description: 'Pioneer novel algorithms, publish at top conferences (NeurIPS, ICML, CVPR), or join research labs (DeepMind, Microsoft Research, IISc).',
    icon: '🔬',
    requiredSkillCount: 15,
    avgSalary: 'Stipend + Fellowship / ₹25-45 LPA R&D',
    tags: ['Research Methodologies', 'Paper Publishing', 'Deep Theory', 'Mathematical Proofs'],
    resources: [
      { title: 'arXiv.org Computer Science & AI Repository', type: 'Research Paper', provider: 'Cornell University' },
      { title: 'Papers With Code (State of the Art Benchmarks)', type: 'Practice', provider: 'Meta AI' },
      { title: 'PMRF (Prime Minister’s Research Fellowship) India', type: 'Official Guide', provider: 'pmrf.in' },
      { title: 'Distill.pub (Visual Explanations of Machine Learning)', type: 'Course', provider: 'Distill' },
    ],
  },
  {
    id: 'software-engineer',
    title: 'Software Architect & SDE',
    category: 'Technical',
    description: 'Design and build resilient, distributed systems, high-concurrency microservices, and web platforms.',
    icon: '💻',
    requiredSkillCount: 15,
    avgSalary: '₹10-22 LPA',
    tags: ['DSA', 'System Design', 'Concurrency', 'Microservices'],
    resources: [
      { title: 'Designing Data-Intensive Applications', type: 'Book', provider: 'Martin Kleppmann' },
      { title: 'NeetCode 150 Algorithms Roadmap', type: 'Practice', provider: 'NeetCode.io' },
      { title: 'System Design Primer', type: 'Course', provider: 'GitHub / Donne Martin' },
    ],
  },
  {
    id: 'cybersecurity-engineer',
    title: 'Cybersecurity & Defence Specialist',
    category: 'Technical',
    description: 'Protect critical infrastructure, perform red/blue teaming, cloud auditing, and cryptographic validation.',
    icon: '🔐',
    requiredSkillCount: 14,
    avgSalary: '₹9-18 LPA',
    tags: ['Network Security', 'Cryptography', 'Linux Forensics', 'CEH / OSCP'],
    resources: [
      { title: 'TryHackMe & HackTheBox Penetration Labs', type: 'Practice', provider: 'HackTheBox' },
      { title: 'Professor Messer Security+ Training', type: 'Course', provider: 'CompTIA' },
      { title: 'OWASP Top 10 Web Application Security', type: 'Official Guide', provider: 'OWASP' },
    ],
  },
]
