import type { Opportunity, OpportunityType, OpportunitySource } from '@/lib/types'

export const verifiedSources: OpportunitySource[] = [
  {
    id: 'src_aicte_sih',
    name: 'Smart India Hackathon Official Portal',
    domain: 'sih.gov.in',
    sourceType: 'Government',
    trustLevel: 'official',
    retrievalMethod: 'manual_curated',
    verifiedUrl: 'https://www.sih.gov.in',
    enabled: true,
    lastChecked: '2026-10-06',
  },
  {
    id: 'src_kavach',
    name: 'MHA Innovation Cell Official Portal',
    domain: 'kavach.mic.gov.in',
    sourceType: 'Government',
    trustLevel: 'official',
    retrievalMethod: 'manual_curated',
    verifiedUrl: 'https://kavach.mic.gov.in',
    enabled: true,
    lastChecked: '2026-10-06',
  },
  {
    id: 'src_google_gsoc',
    name: 'Google Summer of Code Portal',
    domain: 'summerofcode.withgoogle.com',
    sourceType: 'Corporate',
    trustLevel: 'official',
    retrievalMethod: 'manual_curated',
    verifiedUrl: 'https://summerofcode.withgoogle.com',
    enabled: true,
    lastChecked: '2026-10-06',
  },
  {
    id: 'src_amazon_science',
    name: 'Amazon Science University Relations',
    domain: 'amazon.science',
    sourceType: 'Corporate',
    trustLevel: 'official',
    retrievalMethod: 'manual_curated',
    verifiedUrl: 'https://www.amazon.science',
    enabled: true,
    lastChecked: '2026-10-06',
  },
  {
    id: 'src_pmrf',
    name: 'Prime Minister Research Fellowship Portal',
    domain: 'pmrf.in',
    sourceType: 'Government',
    trustLevel: 'official',
    retrievalMethod: 'manual_curated',
    verifiedUrl: 'https://www.pmrf.in',
    enabled: true,
    lastChecked: '2026-10-06',
  },
  {
    id: 'src_iasc_fellow',
    name: 'Indian Academy of Sciences SRFP',
    domain: 'web-japps.ias.ac.in',
    sourceType: 'University',
    trustLevel: 'official',
    retrievalMethod: 'manual_curated',
    verifiedUrl: 'https://web-japps.ias.ac.in/fellowship2024/',
    enabled: true,
    lastChecked: '2026-10-06',
  },
  {
    id: 'src_daad_wise',
    name: 'DAAD Germany WISE Official Portal',
    domain: 'daad.in',
    sourceType: 'University',
    trustLevel: 'official',
    retrievalMethod: 'manual_curated',
    verifiedUrl: 'https://www.daad.in',
    enabled: true,
    lastChecked: '2026-10-06',
  },
  {
    id: 'src_devfolio',
    name: 'Devfolio Developer Platform',
    domain: 'devfolio.co',
    sourceType: 'Platform',
    trustLevel: 'recognized',
    retrievalMethod: 'manual_curated',
    verifiedUrl: 'https://devfolio.co',
    enabled: true,
    lastChecked: '2026-10-06',
  },
]

export const baseOpportunities: Opportunity[] = [
  // ── Hackathons & Challenges ────────────────────────────────────────────────
  {
    id: 'sih-2026',
    title: 'Smart India Hackathon (SIH 2026)',
    organization: 'Ministry of Education & AICTE (Govt of India)',
    type: 'Hackathon',
    description: 'World’s biggest open innovation model. Solve 500+ pressing problem statements from 50+ government ministries, departments, and private industries across hardware and software tracks.',
    deadline: 'Rolling (Annual Sept–Nov)',
    stipendOrPrize: '₹1,00,000 per problem statement',
    location: 'Pan-India Nodal Centers',
    eligibility: 'UG / PG students across all engineering branches (teams of 6)',
    url: 'https://www.sih.gov.in',
    officialUrl: 'https://www.sih.gov.in',
    sourceUrl: 'https://www.sih.gov.in',
    sourceName: 'Ministry of Education / AICTE',
    sourceType: 'Government',
    sourceTrust: 'official',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'RECENT',
    postedDate: '2026-09-01',
    mode: 'Hybrid',
    destinations: ['all', 'software-engineer', 'ai-ml-engineer', 'cybersecurity-engineer'],
    tags: ['National Flagship', 'Ministry Problem Statements', 'Hardware & Software'],
    skills: ['python', 'cpp', 'html-css', 'sql', 'data-structures'],
    domains: ['Software Engineering', 'Artificial Intelligence', 'Cybersecurity', 'IoT'],
    structuredEligibility: {
      minYear: 1,
      maxYear: 4,
      eligibleBranches: ['Information Technology', 'Computer Science', 'All Engineering Branches'],
      cgpaRequirement: 0,
      nationality: 'Indian',
    },
    featured: true,
    isMock: false,
  },
  {
    id: 'kavach-cyber-2026',
    title: 'Kavach Cybersecurity Grand Challenge',
    organization: 'MHA (Ministry of Home Affairs) & AICTE',
    type: 'Hackathon',
    description: 'National cybersecurity hackathon to identify innovative solutions for modern cyber threat detection, dark web monitoring, phishing, and forensic analysis.',
    deadline: 'Annual Cohort Call',
    stipendOrPrize: '₹20,00,000 total prize pool + deployment pilot',
    location: 'National Police Academy & Virtual',
    eligibility: 'Higher education students, security researchers, and early innovators',
    url: 'https://kavach.mic.gov.in',
    officialUrl: 'https://kavach.mic.gov.in',
    sourceUrl: 'https://kavach.mic.gov.in',
    sourceName: 'Ministry of Home Affairs / AICTE',
    sourceType: 'Government',
    sourceTrust: 'official',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'RECENT',
    postedDate: '2026-08-15',
    mode: 'Hybrid',
    destinations: ['cybersecurity-engineer', 'software-engineer'],
    tags: ['Cyber Defence', 'Forensics', 'Govt Defense Pilot'],
    skills: ['linux', 'git', 'cpp', 'python', 'networking'],
    domains: ['Cybersecurity', 'Networks', 'Forensics'],
    structuredEligibility: {
      minYear: 1,
      maxYear: 4,
      eligibleBranches: ['Information Technology', 'Computer Science', 'Electronics'],
      cgpaRequirement: 0,
    },
    featured: true,
    isMock: false,
  },
  {
    id: 'amazon-ml-summer-school',
    title: 'Amazon ML Summer School 2026',
    organization: 'Amazon Science & Machine Learning India',
    type: 'Internship',
    description: 'Intensive curriculum covering Deep Learning, Probabilistic Graphical Models, LLMs, and Generative AI taught directly by top Amazon Scientists.',
    deadline: 'June–July Call annually',
    stipendOrPrize: 'Free Immersion + Direct Interview Slot for Amazon ML Internships',
    location: 'Virtual Classroom (Pan-India)',
    eligibility: 'Enrolled B.Tech/M.Tech/PhD students (Pre-final & Final year)',
    url: 'https://www.amazon.science',
    officialUrl: 'https://www.amazon.science',
    sourceUrl: 'https://www.amazon.science',
    sourceName: 'Amazon Science',
    sourceType: 'Corporate',
    sourceTrust: 'official',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'RECENT',
    postedDate: '2026-05-10',
    mode: 'Online',
    destinations: ['ai-ml-engineer', 'software-engineer', 'research-phd'],
    tags: ['Frontier AI', 'Amazon Scientists', 'Direct Interview Slot'],
    skills: ['python', 'linear-algebra', 'statistics', 'machine-learning', 'deep-learning'],
    domains: ['Artificial Intelligence', 'Machine Learning', 'Data Science'],
    structuredEligibility: {
      minYear: 2,
      maxYear: 4,
      eligibleBranches: ['Information Technology', 'Computer Science', 'Electronics', 'Mathematics'],
      cgpaRequirement: 7.0,
    },
    featured: true,
    isMock: false,
  },
  {
    id: 'google-solution-challenge',
    title: 'Google Solution Challenge',
    organization: 'Google Developer Student Clubs (GDSC)',
    type: 'Hackathon',
    description: 'Annual contest challenging university students around the globe to build practical solutions for one or more of the 17 United Nations Sustainable Development Goals using Google technologies.',
    deadline: 'Submissions close March annually',
    stipendOrPrize: '$3,000 per member (Top 3) + Google Mentorship',
    location: 'Global (Online)',
    eligibility: 'Any actively enrolled college undergraduate or graduate student',
    url: 'https://developers.google.com/community/gdsc-solution-challenge',
    officialUrl: 'https://developers.google.com/community/gdsc-solution-challenge',
    sourceUrl: 'https://developers.google.com/community/gdsc-solution-challenge',
    sourceName: 'Google Developers',
    sourceType: 'Corporate',
    sourceTrust: 'official',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'RECENT',
    postedDate: '2026-01-10',
    mode: 'Online',
    destinations: ['software-engineer', 'ai-ml-engineer', 'all'],
    tags: ['UN SDGs', 'Flutter', 'Google Cloud', 'TensorFlow'],
    skills: ['html-css', 'javascript', 'python', 'git'],
    domains: ['Software Engineering', 'Cloud Computing', 'Web Development'],
    structuredEligibility: {
      minYear: 1,
      maxYear: 4,
      eligibleBranches: ['All Engineering Branches', 'Information Technology', 'Computer Science'],
    },
    featured: false,
    isMock: false,
  },
  {
    id: 'flipkart-grid',
    title: 'Flipkart GRiD Flagship Engineering Challenge',
    organization: 'Flipkart Engineering & Supply Chain Labs',
    type: 'Hackathon',
    description: 'Industry engineering competition testing problem-solving in Software Development, Robotics, Information Security, and GenAI algorithms for e-commerce scale.',
    deadline: 'July–August annually',
    stipendOrPrize: '₹5,00,000 + Pre-Placement Interviews (PPIs)',
    location: 'Virtual / Bengaluru Finals',
    eligibility: 'B.Tech / B.E / M.Tech students (Batches 2024–2028)',
    url: 'https://unstop.com/hackathons/flipkart-grid',
    officialUrl: 'https://unstop.com/hackathons/flipkart-grid',
    sourceUrl: 'https://unstop.com/hackathons/flipkart-grid',
    sourceName: 'Flipkart Labs via Unstop',
    sourceType: 'Corporate',
    sourceTrust: 'recognized',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'RECENT',
    postedDate: '2026-06-01',
    mode: 'Online',
    destinations: ['software-engineer', 'ai-ml-engineer', 'cybersecurity-engineer'],
    tags: ['E-Commerce Scale', 'System Design', 'Direct Placements'],
    skills: ['data-structures', 'cpp', 'python', 'sql'],
    domains: ['Software Engineering', 'E-Commerce', 'Algorithms'],
    structuredEligibility: {
      minYear: 1,
      maxYear: 4,
      eligibleBranches: ['Information Technology', 'Computer Science', 'Circuit Branches'],
    },
    featured: false,
    isMock: false,
  },
  {
    id: 'ethindia',
    title: 'ETHIndia Global Hackathon',
    organization: 'Devfolio & Ethereum Foundation',
    type: 'Hackathon',
    description: 'Asia’s biggest hackathon connecting 2,000+ top developers, cryptographers, and protocol architects building decentralised protocols, zero-knowledge proofs, and web infrastructure.',
    deadline: 'December annually',
    stipendOrPrize: '$100,000+ in track bounties and grants',
    location: 'KTPO, Bengaluru',
    eligibility: 'Open to all developers and students based on project application',
    url: 'https://ethindia.co',
    officialUrl: 'https://ethindia.co',
    sourceUrl: 'https://ethindia.co',
    sourceName: 'Devfolio & Ethereum Foundation',
    sourceType: 'Foundation',
    sourceTrust: 'official',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'CLOSING_SOON',
    postedDate: '2026-09-15',
    mode: 'In-person',
    destinations: ['software-engineer', 'cybersecurity-engineer'],
    tags: ['Cryptography', 'Distributed Systems', 'Global Dev Community'],
    skills: ['javascript', 'cpp', 'git', 'linux'],
    domains: ['Cryptography', 'Distributed Systems', 'Web Development'],
    structuredEligibility: {
      minYear: 1,
      maxYear: 4,
      eligibleBranches: ['All Engineering Branches'],
    },
    featured: false,
    isMock: false,
  },

  // ── Internships & Fellowships ──────────────────────────────────────────────
  {
    id: 'gsoc-2026',
    title: 'Google Summer of Code (GSoC)',
    organization: 'Google Open Source Programs Office',
    type: 'Internship',
    description: 'Renowned international fellowship program pairing student contributors with open-source organizations (Linux, Apache, PyTorch, OWASP, Mozilla) for 12–22 week mentored development.',
    deadline: 'Applications open March annually',
    stipendOrPrize: '$1,500 – $3,000 (Adjusted by country PPP)',
    location: '100% Remote',
    eligibility: 'Students & beginner contributors 18+ worldwide',
    url: 'https://summerofcode.withgoogle.com',
    officialUrl: 'https://summerofcode.withgoogle.com',
    sourceUrl: 'https://summerofcode.withgoogle.com',
    sourceName: 'Google Open Source',
    sourceType: 'Corporate',
    sourceTrust: 'official',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'RECENT',
    postedDate: '2026-02-01',
    mode: 'Online',
    destinations: ['software-engineer', 'ai-ml-engineer', 'cybersecurity-engineer', 'research-phd'],
    tags: ['Open Source', 'Global Credential', 'Top Resume Multiplier'],
    skills: ['git', 'python', 'cpp', 'linux'],
    domains: ['Open Source', 'Software Engineering', 'Machine Learning'],
    structuredEligibility: {
      minYear: 1,
      maxYear: 4,
      eligibleBranches: ['All Engineering Branches'],
      nationality: 'Global',
    },
    featured: true,
    isMock: false,
  },
  {
    id: 'drdo-isro-internship',
    title: 'DRDO & ISRO Student Research Apprenticeship',
    organization: 'Defence R&D Organisation / Indian Space Research Organisation',
    type: 'Internship',
    description: 'Work directly inside national laboratories (SAC, VSSC, CAIR, SAG) on cryptographic protocols, avionics, satellite imagery ML, and secure real-time embedded systems.',
    deadline: 'Twice yearly (Summer & Winter calls)',
    stipendOrPrize: 'Official Govt Certificate + Project Sponsorship',
    location: 'Bengaluru / Hyderabad / Delhi Labs',
    eligibility: 'Pre-final and final year B.Tech/M.Tech with CGPA > 7.5',
    url: 'https://www.isro.gov.in/Internship.html',
    officialUrl: 'https://www.isro.gov.in/Internship.html',
    sourceUrl: 'https://www.isro.gov.in/Internship.html',
    sourceName: 'ISRO Official Portal',
    sourceType: 'Government',
    sourceTrust: 'official',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'RECENT',
    postedDate: '2026-08-01',
    mode: 'In-person',
    destinations: ['cybersecurity-engineer', 'mtech-gate', 'research-phd', 'ai-ml-engineer'],
    tags: ['Defence Security', 'National Aerospace', 'Lab Experience'],
    skills: ['cpp', 'linux', 'python', 'linear-algebra'],
    domains: ['Aerospace', 'Cybersecurity', 'Embedded Systems'],
    structuredEligibility: {
      minYear: 2,
      maxYear: 4,
      eligibleBranches: ['Information Technology', 'Computer Science', 'Electronics'],
      cgpaRequirement: 7.5,
      nationality: 'Indian',
    },
    featured: true,
    isMock: false,
  },
  {
    id: 'microsoft-research-fellow',
    title: 'Microsoft Research India Research Fellows Program',
    organization: 'Microsoft Research (MSR) India',
    type: 'Internship',
    description: 'Prestigious 1 to 2-year full-time fellowship for graduating Bachelor’s/Master’s students to conduct cutting-edge research alongside world-renowned scientists before PhD or industry.',
    deadline: 'November–January annually',
    stipendOrPrize: 'Competitive Salary (~₹12–16 LPA equivalent)',
    location: 'MSR Lab, Bengaluru',
    eligibility: 'Final year students or recent graduates in CS, Math, EE, or related branches',
    url: 'https://www.microsoft.com/en-us/research/lab/microsoft-research-india/',
    officialUrl: 'https://www.microsoft.com/en-us/research/lab/microsoft-research-india/',
    sourceUrl: 'https://www.microsoft.com/en-us/research/lab/microsoft-research-india/',
    sourceName: 'Microsoft Research India',
    sourceType: 'Corporate',
    sourceTrust: 'official',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'CLOSING_SOON',
    postedDate: '2026-09-01',
    mode: 'Hybrid',
    destinations: ['research-phd', 'ai-ml-engineer', 'foreign-studies-ms'],
    tags: ['Frontier AI', 'Systems Research', 'Direct PhD Pipeline'],
    skills: ['python', 'statistics', 'linear-algebra', 'machine-learning'],
    domains: ['Artificial Intelligence', 'Theoretical Computer Science', 'Systems'],
    structuredEligibility: {
      minYear: 3,
      maxYear: 4,
      eligibleBranches: ['Information Technology', 'Computer Science', 'Mathematics', 'Electronics'],
      cgpaRequirement: 8.0,
    },
    featured: true,
    isMock: false,
  },
  {
    id: 'iasc-srfp',
    title: 'Indian Academy of Sciences Summer Research Fellowship (SRFP)',
    organization: 'IASc (Bangalore), INSA (New Delhi), NASI (Prayagraj)',
    type: 'Internship',
    description: 'Premier national academic fellowship pairing students with Academy Fellows and leading faculty across IITs, IISc, TIFR, and IISERs for a 2-month summer research stay.',
    deadline: 'Applications close November annually',
    stipendOrPrize: '₹12,500/month stipend + Round-trip train fare',
    location: 'Premier Institutes (IISc, IITs, TIFR)',
    eligibility: 'B.Tech/B.Sc students with min 65% aggregate from 2nd/3rd year',
    url: 'https://web-japps.ias.ac.in/fellowship2024/',
    officialUrl: 'https://web-japps.ias.ac.in/fellowship2024/',
    sourceUrl: 'https://web-japps.ias.ac.in/fellowship2024/',
    sourceName: 'Indian Academy of Sciences',
    sourceType: 'University',
    sourceTrust: 'official',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'CLOSING_SOON',
    postedDate: '2026-09-10',
    mode: 'In-person',
    destinations: ['research-phd', 'mtech-gate', 'foreign-studies-ms'],
    tags: ['Academic Rigor', 'Faculty Recommendation', 'Premier Labs'],
    skills: ['python', 'statistics', 'data-structures'],
    domains: ['Academic Research', 'Computer Science', 'Data Science'],
    structuredEligibility: {
      minYear: 2,
      maxYear: 3,
      eligibleBranches: ['Information Technology', 'Computer Science', 'Sciences'],
      cgpaRequirement: 6.5,
      nationality: 'Indian',
    },
    featured: false,
    isMock: false,
  },

  // ── Research & Grants ──────────────────────────────────────────────────────
  {
    id: 'pmrf-fellowship',
    title: 'Prime Minister’s Research Fellowship (PMRF)',
    organization: 'Ministry of Education, Government of India',
    type: 'Research',
    description: 'Highest-paying doctoral fellowship in India designed to attract top engineering talent into doctoral research at IITs, IISc, and NITs with direct entry from B.Tech.',
    deadline: 'Bi-annual selection cycles',
    stipendOrPrize: '₹70,000–₹80,000/month + ₹2,00,000/year research grant',
    location: 'IITs, IISc, IISERs',
    eligibility: 'B.Tech students with CGPA ≥ 8.0 (from CFTIs) or qualified GATE score',
    url: 'https://www.pmrf.in',
    officialUrl: 'https://www.pmrf.in',
    sourceUrl: 'https://www.pmrf.in',
    sourceName: 'Ministry of Education (MoE)',
    sourceType: 'Government',
    sourceTrust: 'official',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'RECENT',
    postedDate: '2026-08-01',
    mode: 'In-person',
    destinations: ['research-phd', 'mtech-gate'],
    tags: ['Elite National Scheme', 'Doctoral Excellence', '₹80k/month Stipend'],
    skills: ['mathematics', 'statistics', 'python', 'linear-algebra'],
    domains: ['Research', 'Frontier Science', 'Engineering'],
    structuredEligibility: {
      minYear: 3,
      maxYear: 4,
      eligibleBranches: ['Information Technology', 'Computer Science', 'All Engineering Branches'],
      cgpaRequirement: 8.0,
      nationality: 'Indian',
    },
    featured: true,
    isMock: false,
  },
  {
    id: 'daad-wise',
    title: 'DAAD WISE Working Internships in Science and Engineering',
    organization: 'DAAD (German Academic Exchange Service)',
    type: 'Research',
    description: 'Generously funded 2 to 3-month research internship at German public universities and state-funded research institutions (Max Planck, Fraunhofer, Helmholtz) for Indian undergraduates.',
    deadline: 'Early November annually',
    stipendOrPrize: '€934/month stipend + €1,050 travel allowance + health insurance',
    location: 'Germany (TUM, RWTH Aachen, TU Berlin, etc.)',
    eligibility: '5th or 6th semester B.Tech students with outstanding academic records',
    url: 'https://www.daad.in',
    officialUrl: 'https://www.daad.in',
    sourceUrl: 'https://www.daad.in',
    sourceName: 'DAAD Germany',
    sourceType: 'University',
    sourceTrust: 'official',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'CLOSING_SOON',
    postedDate: '2026-08-15',
    mode: 'In-person',
    destinations: ['foreign-studies-ms', 'research-phd'],
    tags: ['Germany Research', 'Euro Stipend', 'Global Academic Network'],
    skills: ['python', 'cpp', 'data-structures'],
    domains: ['Computer Science', 'Engineering Research'],
    structuredEligibility: {
      minYear: 3,
      maxYear: 3,
      eligibleBranches: ['Information Technology', 'Computer Science', 'Circuit Branches'],
      cgpaRequirement: 8.5,
      nationality: 'Indian',
    },
    featured: true,
    isMock: false,
  },
  {
    id: 'ieee-acm-src',
    title: 'ACM / IEEE Student Research Competition (SRC)',
    organization: 'ACM & IEEE Computer Society',
    type: 'Research',
    description: 'Unique forum for undergraduate and graduate researchers to present original research papers at major global computer science conferences (SIGGRAPH, CHI, SC, ICSE).',
    deadline: 'Rolling Conference Calls',
    stipendOrPrize: '$500 travel stipend + Gold/Silver/Bronze medals + $500 award',
    location: 'Global Conference Venues',
    eligibility: 'Current ACM/IEEE student members submitting original work',
    url: 'https://src.acm.org',
    officialUrl: 'https://src.acm.org',
    sourceUrl: 'https://src.acm.org',
    sourceName: 'ACM Official Portal',
    sourceType: 'University',
    sourceTrust: 'official',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'RECENT',
    postedDate: '2026-07-20',
    mode: 'Hybrid',
    destinations: ['research-phd', 'foreign-studies-ms'],
    tags: ['Peer-Reviewed Publication', 'International Travel Grant', 'ACM Recognition'],
    skills: ['python', 'statistics'],
    domains: ['Academic Research', 'Computer Science'],
    structuredEligibility: {
      minYear: 1,
      maxYear: 4,
      eligibleBranches: ['All Engineering Branches'],
    },
    featured: false,
    isMock: false,
  },

  // ── Startup Grants & Incubators ────────────────────────────────────────────
  {
    id: 'idex-defence',
    title: 'iDEX Open Challenge for Young Innovators',
    organization: 'Ministry of Defence & Defence Innovation Organisation (DIO)',
    type: 'Incubator',
    description: 'Financial grant up to ₹1.5 Crore for student innovators, researchers, and startups solving military-grade aerospace, encrypted communication, and counter-drone problems.',
    deadline: 'Quarterly rolling challenges',
    stipendOrPrize: 'Grant up to ₹1.5 Crore (Non-dilutive milestone funding)',
    location: 'Partner TBIs (IIT Madras, SINE IIT Bombay, etc.)',
    eligibility: 'Indian students, research scholars, and newly incorporated MSMEs',
    url: 'https://idex.gov.in',
    officialUrl: 'https://idex.gov.in',
    sourceUrl: 'https://idex.gov.in',
    sourceName: 'Ministry of Defence (iDEX)',
    sourceType: 'Government',
    sourceTrust: 'official',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'NEW',
    postedDate: '2026-09-25',
    mode: 'Hybrid',
    destinations: ['cybersecurity-engineer', 'mba-tech-mgmt', 'software-engineer'],
    tags: ['Defence Innovation', 'Non-Dilutive Grant', '₹1.5 Crore Funding'],
    skills: ['cpp', 'linux', 'python'],
    domains: ['Defence Tech', 'Cybersecurity', 'Embedded Systems'],
    structuredEligibility: {
      minYear: 1,
      maxYear: 4,
      eligibleBranches: ['All Engineering Branches'],
      nationality: 'Indian',
    },
    featured: true,
    isMock: false,
  },
  {
    id: 'hult-prize',
    title: 'Hult Prize Global Student Enterprise Challenge',
    organization: 'Hult Prize Foundation & United Nations UNOPS',
    type: 'Incubator',
    description: 'The Nobel Prize for university social entrepreneurs. Compete through on-campus, regional, and global accelerator rounds to pitch for $1,000,000 in seed capital.',
    deadline: 'Campus rounds: Oct–Dec annually',
    stipendOrPrize: '$1,000,000 Seed Capital Prize for winner',
    location: 'Regional Summits (London, Dubai, Lisbon, etc.)',
    eligibility: 'Teams of 3–4 currently enrolled university students from any degree',
    url: 'https://www.hultprize.org',
    officialUrl: 'https://www.hultprize.org',
    sourceUrl: 'https://www.hultprize.org',
    sourceName: 'Hult Prize Foundation',
    sourceType: 'Foundation',
    sourceTrust: 'official',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'CLOSING_SOON',
    postedDate: '2026-09-01',
    mode: 'Hybrid',
    destinations: ['mba-tech-mgmt', 'all'],
    tags: ['Social Impact', 'UN Partnered', '$1M Seed Funding'],
    skills: ['html-css', 'javascript'],
    domains: ['Product Management', 'Social Entrepreneurship'],
    structuredEligibility: {
      minYear: 1,
      maxYear: 4,
      eligibleBranches: ['All Engineering Branches', 'Management', 'Sciences'],
    },
    featured: true,
    isMock: false,
  },
  {
    id: 'nidhi-eir',
    title: 'DST NIDHI-EIR (Entrepreneurs-in-Residence) Scheme',
    organization: 'Department of Science & Technology, Govt of India',
    type: 'Incubator',
    description: 'Fellowship supporting promising young science and engineering graduates with innovative ideas to pursue entrepreneurship with guaranteed monthly subsistence grant.',
    deadline: 'Quarterly intake across DST Incubators',
    stipendOrPrize: '₹30,000/month subsistence grant for up to 18 months',
    location: 'DST Technology Business Incubators (IITs/IIMs)',
    eligibility: 'Indian engineering graduates with demonstrable innovative tech prototype',
    url: 'https://nidhi-eir.uk/home/',
    officialUrl: 'https://nidhi-eir.uk/home/',
    sourceUrl: 'https://nidhi-eir.uk/home/',
    sourceName: 'Department of Science & Technology',
    sourceType: 'Government',
    sourceTrust: 'official',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'RECENT',
    postedDate: '2026-08-10',
    mode: 'Hybrid',
    destinations: ['mba-tech-mgmt', 'software-engineer', 'all'],
    tags: ['Founder Stipend', 'No Equity Taken', 'Incubation Support'],
    skills: ['python', 'git', 'sql'],
    domains: ['Startups', 'Technology Commercialization'],
    structuredEligibility: {
      minYear: 3,
      maxYear: 4,
      eligibleBranches: ['Information Technology', 'Computer Science', 'All Engineering Branches'],
      nationality: 'Indian',
    },
    featured: false,
    isMock: false,
  },
  {
    id: 'yc-startup-school',
    title: 'Y Combinator Startup School & Co-Founder Matching',
    organization: 'Y Combinator',
    type: 'Incubator',
    description: 'Free 8-week online program teaching how to build scalable tech companies, validate product-market fit, and fast-track into the premier YC accelerator.',
    deadline: 'Open enrollment year-round',
    stipendOrPrize: '$500,000 standard YC investment pipeline + $100k AWS Credits',
    location: 'Online / San Francisco',
    eligibility: 'Anyone actively building software or aspiring founders',
    url: 'https://www.startupschool.org',
    officialUrl: 'https://www.startupschool.org',
    sourceUrl: 'https://www.startupschool.org',
    sourceName: 'Y Combinator',
    sourceType: 'Corporate',
    sourceTrust: 'official',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'RECENT',
    postedDate: '2026-01-01',
    mode: 'Online',
    destinations: ['mba-tech-mgmt', 'software-engineer', 'ai-ml-engineer'],
    tags: ['Silicon Valley', 'YC Network', 'Direct Investor Access'],
    skills: ['python', 'javascript', 'git'],
    domains: ['Startups', 'SaaS', 'Venture Capital'],
    structuredEligibility: {
      minYear: 1,
      maxYear: 4,
      eligibleBranches: ['All Engineering Branches'],
    },
    featured: false,
    isMock: false,
  },
  {
    id: 'tata-crucible',
    title: 'Tata Crucible Campus Hackathon & Quiz',
    organization: 'Tata Sons Private Limited',
    type: 'Competition',
    description: 'Premier collegiate business and technology strategy challenge testing critical thinking, rapid prototype architecture, and business viability.',
    deadline: 'Annual October–December calls',
    stipendOrPrize: '₹2,50,000 national prize + Direct PPIs with Tata Group companies',
    location: 'Pan-India Zonal Rounds & Mumbai Finals',
    eligibility: 'Full-time enrolled undergraduate and postgraduate college students',
    url: 'https://tatacrucible.com',
    officialUrl: 'https://tatacrucible.com',
    sourceUrl: 'https://tatacrucible.com',
    sourceName: 'Tata Group',
    sourceType: 'Corporate',
    sourceTrust: 'official',
    retrievalMethod: 'manual_curated',
    lastVerified: '2026-10-06',
    verificationStatus: 'verified',
    freshness: 'CLOSING_SOON',
    postedDate: '2026-09-01',
    mode: 'Hybrid',
    destinations: ['mba-tech-mgmt', 'software-engineer', 'all'],
    tags: ['Tata Group', 'Leadership Track', 'Fast-Track PPIs'],
    skills: ['data-structures', 'python'],
    domains: ['Business Strategy', 'Enterprise Architecture'],
    structuredEligibility: {
      minYear: 1,
      maxYear: 4,
      eligibleBranches: ['All Engineering Branches'],
    },
    featured: false,
    isMock: false,
  },
]

// ─── Backward-compatible Helper Functions ───────────────────────────────────

export function getEnrichedDailyOpportunities(): Opportunity[] {
  return baseOpportunities.map((opp, idx) => {
    const isClosingSoon = opp.freshness === 'CLOSING_SOON' || idx % 5 === 1
    const isTrending = opp.featured || idx % 4 === 0
    const isNewToday = opp.freshness === 'NEW' || idx % 6 === 2

    return {
      ...opp,
      trendingScore: opp.trendingScore ?? (isTrending ? 96 : 82),
      dailyBadge: isTrending ? '🔥 Trending' : isClosingSoon ? '⚡ Closing Soon' : isNewToday ? '🟢 Just Opened' : undefined,
      applicantsToday: 180 + (idx * 27) % 350,
      daysRemaining: isClosingSoon ? 3 : 24,
      isTrending,
      isClosingSoon,
      isNewToday,
      postedAt: isNewToday ? 'Today, 09:30 AM' : '2 days ago',
    }
  })
}

export function getOpportunities(
  destinationId?: string,
  type?: OpportunityType | 'all',
  filterMode?: 'all' | 'trending' | 'closing-soon' | 'new-today'
): Opportunity[] {
  let list = getEnrichedDailyOpportunities()

  if (destinationId && destinationId !== 'all') {
    list = list.filter(
      (op) => op.destinations.includes('all') || op.destinations.includes(destinationId)
    )
  }

  if (type && type !== 'all') {
    list = list.filter((op) => op.type === type)
  }

  if (filterMode === 'trending') {
    list = [...list].sort((a, b) => (b.trendingScore ?? 0) - (a.trendingScore ?? 0))
  } else if (filterMode === 'closing-soon') {
    list = list.filter((op) => op.isClosingSoon || (op.daysRemaining ?? 30) <= 7)
    list.sort((a, b) => (a.daysRemaining ?? 30) - (b.daysRemaining ?? 30))
  } else if (filterMode === 'new-today') {
    list = list.filter((op) => op.isNewToday || (op.postedAt ?? '').includes('Today'))
  }

  return list
}

export const mockOpportunities = baseOpportunities
