import type { Skill } from '@/lib/types'

export const mockSkills: Skill[] = [
  // ── Already completed ──────────────────────────────────────────────
  {
    id: 'python',
    name: 'Python',
    category: 'Programming',
    description: 'General-purpose programming language widely used in data science, systems, and ML.',
    currentLevel: 'Intermediate',
    requiredLevel: 'Intermediate',
    status: 'completed',
    priority: 'critical',
    prerequisites: [],
    dependents: ['data-structures', 'data-analysis', 'machine-learning'],
    estimatedWeeks: 0,
    whyItMatters: 'Python is the primary lingua franca for ML/AI and rapid prototyping. Prerequisite for 6 downstream skills.',
    resources: [
      { title: 'Python for Data Analysis (3rd Edition)', type: 'Book', provider: "Wes McKinney (O'Reilly)" },
      { title: 'Official Python Documentation & Tutorial', type: 'Official Guide', provider: 'python.org' },
    ],
  },
  {
    id: 'cpp',
    name: 'C++',
    category: 'Programming',
    description: 'High-performance compiled language, standard for algorithms and competitive coding.',
    currentLevel: 'Intermediate',
    requiredLevel: 'Beginner',
    status: 'completed',
    priority: 'recommended',
    prerequisites: [],
    dependents: ['data-structures'],
    estimatedWeeks: 0,
    whyItMatters: 'Provides deep intuition about memory management, pointers, and cache efficiency.',
    resources: [
      { title: 'LearnCpp.com Free Comprehensive Guide', type: 'Course', provider: 'LearnCpp' },
    ],
  },
  {
    id: 'html-css',
    name: 'HTML / CSS',
    category: 'Programming',
    description: 'Foundational web technologies for building interactive browser interfaces.',
    currentLevel: 'Intermediate',
    requiredLevel: 'Beginner',
    status: 'completed',
    priority: 'recommended',
    prerequisites: [],
    dependents: [],
    estimatedWeeks: 0,
    whyItMatters: 'Useful for building frontend dashboards and presenting data projects to stakeholders.',
    resources: [
      { title: 'MDN Web Docs (HTML/CSS Guide)', type: 'Official Guide', provider: 'Mozilla' },
    ],
  },
  {
    id: 'git',
    name: 'Git',
    category: 'Tools',
    description: 'Distributed version control system for tracking code changes and team collaboration.',
    currentLevel: 'Beginner',
    requiredLevel: 'Beginner',
    status: 'completed',
    priority: 'recommended',
    prerequisites: [],
    dependents: ['mlops'],
    estimatedWeeks: 0,
    whyItMatters: 'Crucial for managing repositories, continuous integration, and open-source contributions.',
    resources: [
      { title: 'Pro Git Book (Free Online)', type: 'Book', provider: 'Scott Chacon & Ben Straub' },
    ],
  },

  // ── Skill Gaps ──────────────────────────────────────────────────────
  {
    id: 'data-structures',
    name: 'Data Structures',
    category: 'Foundations',
    description: 'Fundamental structures (Trees, Graphs, Hashmaps, Heaps) for organizing and accessing data efficiently.',
    currentLevel: 'Beginner',
    requiredLevel: 'Intermediate',
    status: 'next',
    priority: 'critical',
    prerequisites: ['python'],
    dependents: ['machine-learning', 'sql'],
    estimatedWeeks: 3,
    whyItMatters: 'Data structures underpin algorithm efficiency and are required in technical interviews, GATE CS, and ML architectures.',
    resources: [
      { title: 'NeetCode 150 Core DSA Patterns', type: 'Practice', provider: 'NeetCode.io' },
      { title: 'Algorithms, Part I & II (Sedgewick)', type: 'Course', provider: 'Princeton / Coursera' },
      { title: 'Introduction to Algorithms (CLRS)', type: 'Book', provider: 'MIT Press' },
    ],
  },
  {
    id: 'statistics',
    name: 'Statistics & Probability',
    category: 'Mathematics',
    description: 'Probability distributions, Bayes theorem, hypothesis testing, and statistical inference.',
    currentLevel: 'None',
    requiredLevel: 'Intermediate',
    status: 'locked',
    priority: 'critical',
    prerequisites: ['linear-algebra'],
    dependents: ['machine-learning', 'data-analysis'],
    estimatedWeeks: 4,
    whyItMatters: 'Statistics is the mathematical engine of ML. Necessary for loss functions, p-values, and model validation.',
    resources: [
      { title: 'StatQuest with Josh Starmer (ML & Stats)', type: 'Course', provider: 'YouTube / StatQuest' },
      { title: 'Introduction to Probability (Blitzstein & Hwang)', type: 'Book', provider: 'Harvard University' },
      { title: 'Khan Academy College Statistics', type: 'Practice', provider: 'Khan Academy' },
    ],
  },
  {
    id: 'linear-algebra',
    name: 'Linear Algebra',
    category: 'Mathematics',
    description: 'Vectors, matrix multiplications, eigenvalues, eigenvectors, and geometric transformations.',
    currentLevel: 'None',
    requiredLevel: 'Intermediate',
    status: 'locked',
    priority: 'critical',
    prerequisites: [],
    dependents: ['statistics', 'machine-learning', 'deep-learning'],
    estimatedWeeks: 4,
    whyItMatters: 'Neural networks, embeddings, PCA dimensionality reduction, and quantum computing rely entirely on linear algebra.',
    resources: [
      { title: 'Essence of Linear Algebra (3Blue1Brown)', type: 'Course', provider: '3Blue1Brown' },
      { title: 'MIT 18.06 Linear Algebra (Gilbert Strang)', type: 'Course', provider: 'MIT OpenCourseWare' },
      { title: 'Linear Algebra Done Right (Axler)', type: 'Book', provider: 'Springer' },
    ],
  },
  {
    id: 'sql',
    name: 'SQL & Relational DBs',
    category: 'Databases',
    description: 'Structured Query Language for querying, indexing, and aggregating data from relational databases.',
    currentLevel: 'None',
    requiredLevel: 'Intermediate',
    status: 'locked',
    priority: 'high',
    prerequisites: ['data-structures'],
    dependents: ['data-analysis'],
    estimatedWeeks: 2,
    whyItMatters: 'Over 90% of real-world corporate data sits in relational warehouses. Essential for data ingestion in industry and CAT/MBA data analytics.',
    resources: [
      { title: 'Mode Analytics SQL Tutorial', type: 'Practice', provider: 'Mode.com' },
      { title: 'LeetCode 50 SQL Study Plan', type: 'Practice', provider: 'LeetCode' },
    ],
  },
  {
    id: 'data-analysis',
    name: 'Data Analysis & EDA',
    category: 'Data Science',
    description: 'Exploratory data analysis, cleaning, feature engineering, and visualization with pandas and seaborn.',
    currentLevel: 'None',
    requiredLevel: 'Intermediate',
    status: 'locked',
    priority: 'high',
    prerequisites: ['python', 'sql', 'statistics'],
    dependents: ['machine-learning'],
    estimatedWeeks: 3,
    whyItMatters: 'Raw data is noisy and imperfect. EDA is how you clean datasets before passing them to neural models.',
    resources: [
      { title: 'Kaggle Micro-courses (Pandas & Data Cleaning)', type: 'Practice', provider: 'Kaggle' },
      { title: 'Data Analysis with Python (freeCodeCamp)', type: 'Course', provider: 'freeCodeCamp' },
    ],
  },
  {
    id: 'machine-learning',
    name: 'Machine Learning Core',
    category: 'Machine Learning',
    description: 'Supervised, unsupervised, ensemble methods, decision trees, SVMs, and gradient boosting.',
    currentLevel: 'None',
    requiredLevel: 'Advanced',
    status: 'locked',
    priority: 'critical',
    prerequisites: ['python', 'data-structures', 'statistics', 'linear-algebra', 'data-analysis'],
    dependents: ['deep-learning', 'nlp', 'computer-vision'],
    estimatedWeeks: 6,
    whyItMatters: 'The central milestone of AI Engineering. Everything in classical data science and modern AI builds from this skill.',
    resources: [
      { title: 'Machine Learning Specialization by Andrew Ng', type: 'Course', provider: 'DeepLearning.AI / Coursera' },
      { title: 'Hands-On ML with Scikit-Learn & PyTorch', type: 'Book', provider: "O'Reilly Media" },
    ],
  },
  {
    id: 'deep-learning',
    name: 'Deep Learning & Neural Nets',
    category: 'Machine Learning',
    description: 'Multi-layer perceptrons, backpropagation, CNNs, RNNs, and Attention/Transformer architectures.',
    currentLevel: 'None',
    requiredLevel: 'Intermediate',
    status: 'locked',
    priority: 'high',
    prerequisites: ['machine-learning', 'linear-algebra'],
    dependents: ['nlp', 'computer-vision'],
    estimatedWeeks: 5,
    whyItMatters: 'Deep Learning powers generative AI, computer vision, speech synthesis, and modern frontier models.',
    resources: [
      { title: 'Deep Learning Book (Goodfellow, Bengio, Courville)', type: 'Book', provider: 'MIT Press' },
      { title: 'Practical Deep Learning for Coders (Fast.ai)', type: 'Course', provider: 'Fast.ai' },
    ],
  },
  {
    id: 'nlp',
    name: 'Natural Language Processing',
    category: 'Machine Learning',
    description: 'Tokenization, embeddings, language modeling, fine-tuning, and Transformer architectures.',
    currentLevel: 'None',
    requiredLevel: 'Beginner',
    status: 'locked',
    priority: 'recommended',
    prerequisites: ['deep-learning'],
    dependents: [],
    estimatedWeeks: 3,
    whyItMatters: 'Powers Large Language Models (LLMs), semantic search, conversational agents, and machine translation.',
    resources: [
      { title: 'Stanford CS224N: NLP with Deep Learning', type: 'Course', provider: 'Stanford University' },
      { title: 'Hugging Face NLP Course (Free)', type: 'Practice', provider: 'HuggingFace.co' },
    ],
  },
  {
    id: 'computer-vision',
    name: 'Computer Vision',
    category: 'Machine Learning',
    description: 'Image processing, convolution kernels, object detection (YOLO), segmentation, and generative diffusion.',
    currentLevel: 'None',
    requiredLevel: 'Beginner',
    status: 'locked',
    priority: 'recommended',
    prerequisites: ['deep-learning'],
    dependents: [],
    estimatedWeeks: 3,
    whyItMatters: 'Applied across autonomous driving, robotics, biomedical imaging, and satellite analytics.',
    resources: [
      { title: 'Stanford CS231n: Deep Learning for Computer Vision', type: 'Course', provider: 'Stanford University' },
    ],
  },
  {
    id: 'mlops',
    name: 'MLOps & Deployment',
    category: 'Tools',
    description: 'Containerizing models with Docker, experiment tracking with MLflow, FastAPI serving, and CI/CD pipelines.',
    currentLevel: 'None',
    requiredLevel: 'Beginner',
    status: 'locked',
    priority: 'recommended',
    prerequisites: ['machine-learning', 'git'],
    dependents: [],
    estimatedWeeks: 3,
    whyItMatters: 'Bridges theoretical ML notebooks and scalable, high-availability production services.',
    resources: [
      { title: 'Made With ML (Goku Mohandas)', type: 'Course', provider: 'madewithml.com' },
      { title: 'Full Stack Deep Learning Course', type: 'Course', provider: 'FSDL' },
    ],
  },
  {
    id: 'cloud-basics',
    name: 'Cloud Computing (AWS / GCP)',
    category: 'Tools',
    description: 'Virtual machines, object storage (S3), serverless compute, and container orchestration.',
    currentLevel: 'None',
    requiredLevel: 'Beginner',
    status: 'locked',
    priority: 'recommended',
    prerequisites: ['git'],
    dependents: ['mlops'],
    estimatedWeeks: 2,
    whyItMatters: 'Industry workflows almost exclusively operate on AWS, Azure, or Google Cloud.',
    resources: [
      { title: 'AWS Cloud Practitioner Essentials', type: 'Course', provider: 'Amazon Web Services' },
    ],
  },
]

export const getSkillById = (id: string): Skill | undefined =>
  mockSkills.find((s) => s.id === id)

export const getCurrentSkills = (currentSkillIds: string[]): Skill[] =>
  mockSkills.filter((s) => currentSkillIds.includes(s.id))

export const getSkillGaps = (currentSkillIds: string[]): Skill[] =>
  mockSkills.filter(
    (s) => !currentSkillIds.includes(s.id) && s.status !== 'completed'
  )